asdata.o: asdata.c asm.h
asexpr.o: asexpr.c asm.h
aslex.o: aslex.c asm.h
aslist.o: aslist.c asm.h
asmain.o: asmain.c asm.h gb.h
asout.o: asout.c asm.h
assubr.o: assubr.c asm.h
assym.o: assym.c asm.h
gbadr.o: gbadr.c asm.h gb.h
gbext.o: gbext.c asm.h gb.h
gbmch.o: gbmch.c asm.h gb.h
gbpst.o: gbpst.c asm.h gb.h
